In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd /content/drive/"MyDrive/Colab Notebooks/images"

/content/drive/MyDrive/Colab Notebooks/images


In [ ]:
import plotly.express as px
import os
import skimage.io
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
#importing required libraries
from skimage.io import imread, imshow
from skimage.transform import resize
from skimage.feature import hog
from skimage import exposure
%matplotlib inline

In [ ]:
x_train = list()
y_train = list()



In [ ]:
import glob
import cv2


for directory_path in glob.glob("/content/drive/MyDrive/Colab Notebooks/images/train/*"):
  label = directory_path.split("\\")[-1]
  print(label)
  for img_path in glob.glob(os.path.join(directory_path,"*.jpg")):
    print(img_path)
    img= cv2.imread(img_path,cv2.IMREAD_COLOR)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    #img = img.reshape(-1)
    fd, hog_image = hog(img, orientations=9, pixels_per_cell=(8, 8), 
                    cells_per_block=(2, 2), visualize=True, multichannel=True)
    hog_image_rescaled = exposure.rescale_intensity(hog_image, in_range=(0, 10))
    x_train.append(hog_image_rescaled)#append all the image in imge
    y_train.append(label)#append all the class in classes


/content/drive/MyDrive/Colab Notebooks/images/train/crazing
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_132.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_38.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_13.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_30.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_166.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_4.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_29.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_105.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_141.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_142.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_12.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_97.jpg
/content/drive/MyDrive/Colab Noteboo

In [ ]:
x_test = list()
y_test = list()

for directory_path in glob.glob("/content/drive/MyDrive/Colab Notebooks/images/test/*"):
  label = directory_path.split("\\")[-1]
  print(label)
  for img_path in glob.glob(os.path.join(directory_path,"*.jpg")):
    print(img_path)
    img= cv2.imread(img_path,cv2.IMREAD_COLOR)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    #img = img.reshape(-1)
    fd, hog_image = hog(img, orientations=9, pixels_per_cell=(8, 8), 
                    cells_per_block=(2, 2), visualize=True, multichannel=True)
    hog_image_rescaled = exposure.rescale_intensity(hog_image, in_range=(0, 10))
    x_test.append(hog_image_rescaled)#append all the image in imge
    y_test.append(label)#append all the class in classes


/content/drive/MyDrive/Colab Notebooks/images/test/patches _test
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_208.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_207.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_182.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_178.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_200.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_177.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_186.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_218.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_227.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_194.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_169.jpg
/content/drive/MyDrive/Colab Notebooks/image

In [ ]:
import numpy as np
x_train=np.array(x_train)
y_train=np.array(y_train)
x_test=np.array(x_test)
y_test=np.array(y_test)


In [ ]:
nsamples, nx, ny = x_train.shape
x_train = x_train.reshape((nsamples,nx*ny))
nsamples, nx, ny = x_test.shape
x_test = x_test.reshape((nsamples,nx*ny))

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
le.fit(y_test)
y_test = le.transform(y_test)

In [ ]:
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
model = svm.SVC()
model.fit(x_train, y_train)
 
# print prediction results
predictions = model.predict(x_test)
print(classification_report(y_test, predictions))


              precision    recall  f1-score   support

           0       0.96      0.92      0.94        72
           1       0.68      0.92      0.78        72
           2       0.84      0.88      0.86        72
           3       0.87      0.72      0.79        72
           4       1.00      1.00      1.00        72
           5       0.93      0.76      0.84        72

    accuracy                           0.87       432
   macro avg       0.88      0.87      0.87       432
weighted avg       0.88      0.87      0.87       432



In [ ]:
poly = svm.SVC(kernel="poly")
poly.fit(x_train, y_train)

SVC(kernel='poly')

In [ ]:
from sklearn.model_selection import GridSearchCV

# defining parameter range
#param_grid = {'C': [1, 10, 100, 1000]}
param_grid = {'kernel': ['rbf','linear','poly','sigmoid']}
param_grid_1 = {'degree': [1, 2, 3,4,5,6,7,8,9]}


grid = GridSearchCV(model, param_grid, refit = True, verbose = 3)
grid_poly = GridSearchCV(poly, param_grid_1, refit = True, verbose = 3)
# fitting the model for grid search
grid.fit(x_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV 1/5] END ........................kernel=rbf;, score=0.822 total time=  24.5s
[CV 2/5] END ........................kernel=rbf;, score=0.837 total time=  24.7s
[CV 3/5] END ........................kernel=rbf;, score=0.827 total time=  28.3s
[CV 4/5] END ........................kernel=rbf;, score=0.836 total time=  38.1s
[CV 5/5] END ........................kernel=rbf;, score=0.806 total time=  25.2s
[CV 1/5] END .....................kernel=linear;, score=0.827 total time=  14.4s
[CV 2/5] END .....................kernel=linear;, score=0.817 total time=  13.8s
[CV 3/5] END .....................kernel=linear;, score=0.827 total time=  14.1s
[CV 4/5] END .....................kernel=linear;, score=0.856 total time=  13.8s
[CV 5/5] END .....................kernel=linear;, score=0.856 total time=  14.7s
[CV 1/5] END .......................kernel=poly;, score=0.718 total time=  14.5s
[CV 2/5] END .......................kernel=poly;,

GridSearchCV(estimator=SVC(),
             param_grid={'kernel': ['rbf', 'linear', 'poly', 'sigmoid']},
             verbose=3)

In [ ]:
grid_poly.fit(x_train, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV 1/5] END ..........................degree=1;, score=0.733 total time=  15.3s
[CV 2/5] END ..........................degree=1;, score=0.757 total time=  15.5s
[CV 3/5] END ..........................degree=1;, score=0.748 total time=  15.4s
[CV 4/5] END ..........................degree=1;, score=0.751 total time=  15.6s
[CV 5/5] END ..........................degree=1;, score=0.756 total time=  15.4s
[CV 1/5] END ..........................degree=2;, score=0.767 total time=  14.5s
[CV 2/5] END ..........................degree=2;, score=0.792 total time=  14.6s
[CV 3/5] END ..........................degree=2;, score=0.782 total time=  14.8s
[CV 4/5] END ..........................degree=2;, score=0.816 total time=  14.9s
[CV 5/5] END ..........................degree=2;, score=0.756 total time=  14.9s
[CV 1/5] END ..........................degree=3;, score=0.718 total time=  14.9s
[CV 2/5] END ..........................degree=3;,

GridSearchCV(estimator=SVC(kernel='poly'),
             param_grid={'degree': [1, 2, 3, 4, 5, 6, 7, 8, 9]}, verbose=3)

In [ ]:
# print best parameter after tuning
print(grid.best_params_)

# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

{'kernel': 'rbf'}
SVC()


In [ ]:
# print best parameter after tuning
print(grid_poly.best_params_)

# print how our model looks after hyper-parameter tuning
print(grid_poly.best_estimator_)

{'degree': 2}
SVC(degree=2, kernel='poly')


In [ ]:
from sklearn.model_selection import GridSearchCV

# defining parameter range
param_grid = {'C': [1, 10, 100, 1000]}
#param_grid = {'kernel': ['rbf','linear','poly','sigmoid']}
#param_grid_1 = {'degree': [1, 2, 3,4,5,6,7,8,9]}


grid = GridSearchCV(model, param_grid, refit = True, verbose = 3)
#grid_poly = GridSearchCV(poly, param_grid_1, refit = True, verbose = 3)
# fitting the model for grid search
grid.fit(x_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV 1/5] END ...............................C=1;, score=0.822 total time=  25.5s
[CV 2/5] END ...............................C=1;, score=0.837 total time=  49.7s
[CV 3/5] END ...............................C=1;, score=0.827 total time=  32.5s
[CV 4/5] END ...............................C=1;, score=0.836 total time=  24.7s
[CV 5/5] END ...............................C=1;, score=0.806 total time=  25.3s
[CV 1/5] END ..............................C=10;, score=0.896 total time=  23.5s
[CV 2/5] END ..............................C=10;, score=0.881 total time=  23.3s
[CV 3/5] END ..............................C=10;, score=0.881 total time=  23.3s
[CV 4/5] END ..............................C=10;, score=0.905 total time=  23.6s
[CV 5/5] END ..............................C=10;, score=0.881 total time=  24.0s
[CV 1/5] END .............................C=100;, score=0.911 total time=  24.6s
[CV 2/5] END .............................C=100;,

GridSearchCV(estimator=SVC(), param_grid={'C': [1, 10, 100, 1000]}, verbose=3)

In [ ]:
# print best parameter after tuning
print(grid.best_params_)

# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

{'C': 100}
SVC(C=100)


In [ ]:
poly = svm.SVC(kernel='poly', degree=2, C=1).fit(x_train, y_train)
y_pred=poly.predict(x_test)
print("Polynomial Classifier-->",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Polynomial Classifier--> 0.7777777777777778
[[61  0 11  0  0  0]
 [ 0 65  0  0  0  7]
 [ 4  0 60  8  0  0]
 [ 0 14  3 48  0  7]
 [ 0  0  0  1 71  0]
 [ 0 41  0  0  0 31]]
              precision    recall  f1-score   support

           0       0.94      0.85      0.89        72
           1       0.54      0.90      0.68        72
           2       0.81      0.83      0.82        72
           3       0.84      0.67      0.74        72
           4       1.00      0.99      0.99        72
           5       0.69      0.43      0.53        72

    accuracy                           0.78       432
   macro avg       0.80      0.78      0.78       432
weighted avg       0.80      0.78      0.78       432



In [ ]:
rbf = svm.SVC(kernel='rbf', C=100).fit(x_train, y_train)
y_pred=rbf.predict(x_test)
print("RBF Classifier-->",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

RBF Classifier--> 0.9259259259259259
[[70  0  2  0  0  0]
 [ 0 66  0  3  0  3]
 [ 1  0 70  1  0  0]
 [ 0 10  5 54  0  3]
 [ 0  0  0  0 72  0]
 [ 0  4  0  0  0 68]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98        72
           1       0.82      0.92      0.87        72
           2       0.91      0.97      0.94        72
           3       0.93      0.75      0.83        72
           4       1.00      1.00      1.00        72
           5       0.92      0.94      0.93        72

    accuracy                           0.93       432
   macro avg       0.93      0.93      0.92       432
weighted avg       0.93      0.93      0.92       432

