In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import plotly.express as px
import os
import skimage.io
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets

In [3]:
x_train = list()
y_train = list()



In [4]:
import glob
import cv2


for directory_path in glob.glob("/content/drive/MyDrive/Colab Notebooks/images/train/*"):
  label = directory_path.split("\\")[-1]
  print(label)
  for img_path in glob.glob(os.path.join(directory_path,"*.jpg")):
    print(img_path)
    img= cv2.imread(img_path,cv2.IMREAD_COLOR)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    img = img.reshape(-1)
    x_train.append(img)#append all the image in imge
    y_train.append(label)#append all the class in classes


/content/drive/MyDrive/Colab Notebooks/images/train/crazing
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_132.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_38.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_13.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_30.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_166.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_4.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_29.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_105.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_141.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_142.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_12.jpg
/content/drive/MyDrive/Colab Notebooks/images/train/crazing/crazing_97.jpg
/content/drive/MyDrive/Colab Noteboo

In [5]:
x_test = list()
y_test = list()

for directory_path in glob.glob("/content/drive/MyDrive/Colab Notebooks/images/test/*"):
  label = directory_path.split("\\")[-1]
  print(label)
  for img_path in glob.glob(os.path.join(directory_path,"*.jpg")):
    print(img_path)
    img= cv2.imread(img_path,cv2.IMREAD_COLOR)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    img = img.reshape(-1)
    x_test.append(img)#append all the image in imge
    y_test.append(label)#append all the class in classes


/content/drive/MyDrive/Colab Notebooks/images/test/patches _test
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_208.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_207.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_182.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_178.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_200.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_177.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_186.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_218.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_227.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_194.jpg
/content/drive/MyDrive/Colab Notebooks/images/test/patches _test/patches_169.jpg
/content/drive/MyDrive/Colab Notebooks/image

In [6]:
import numpy as np
x_train=np.array(x_train)
y_train=np.array(y_train)
x_test=np.array(x_test)
y_test=np.array(y_test)


In [7]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
le.fit(y_test)
y_test = le.transform(y_test)

In [8]:
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [9]:
model = svm.SVC()
model.fit(x_train, y_train)
 
# print prediction results
predictions = model.predict(x_test)
print(classification_report(y_test, predictions))


              precision    recall  f1-score   support

           0       0.94      0.61      0.74        72
           1       0.36      0.74      0.48        72
           2       0.99      0.99      0.99        72
           3       0.76      0.71      0.73        72
           4       0.74      0.43      0.54        72
           5       0.46      0.36      0.41        72

    accuracy                           0.64       432
   macro avg       0.71      0.64      0.65       432
weighted avg       0.71      0.64      0.65       432



In [ ]:
from sklearn.model_selection import GridSearchCV

# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
			'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
			'kernel': ['rbf','linear','poly','sigmoid']}

grid = GridSearchCV(model, param_grid, refit = True, verbose = 3)

# fitting the model for grid search
grid.fit(x_train, y_train)


Fitting 5 folds for each of 100 candidates, totalling 500 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.163 total time= 3.2min
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.163 total time= 3.1min
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.163 total time= 3.2min
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.164 total time= 3.2min
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.164 total time= 3.2min
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.431 total time= 2.1min
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.510 total time= 2.2min
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.490 total time= 2.2min
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.522 total time= 2.2min
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.507 total time= 2.1min
[CV 1/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.579 total time= 1.8min
[CV 2/5] END .......C=0.1, gamma=1, kernel=pol

In [ ]:
# print best parameter after tuning
print(grid.best_params_)

# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)


In [ ]:
grid_predictions = grid.predict(x_test)

# print classification report
print(classification_report(y_test, grid_predictions))


In [ ]:
linear = svm.SVC(kernel='linear', C=1).fit(x_train, y_train)
y_pred=linear.predict(x_test)
#print("Linear Classifier -->",accuracy_score(y_test,y_pred))
#print(confusion_matrix(y_test,y_pred))
#print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test,y_pred))


[[ 4 15  6 27 18  2]
 [ 0 48  0 15  1  8]
 [ 4  7 33 11 14  3]
 [ 0  6  0 51  2 13]
 [ 0 42  5  8 12  5]
 [ 0 48  0  2  0 22]]
              precision    recall  f1-score   support

           0       0.50      0.06      0.10        72
           1       0.29      0.67      0.40        72
           2       0.75      0.46      0.57        72
           3       0.45      0.71      0.55        72
           4       0.26      0.17      0.20        72
           5       0.42      0.31      0.35        72

    accuracy                           0.39       432
   macro avg       0.44      0.39      0.36       432
weighted avg       0.44      0.39      0.36       432

0.39351851851851855


In [ ]:
rbf = svm.SVC(kernel='rbf', gamma=0.5, C=1).fit(x_train, y_train)
y_pred=rbf.predict(x_test)
print("RBF -->",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

RBF --> 0.16666666666666666
[[ 0  0  0  0  0 72]
 [ 0  0  0  0  0 72]
 [ 0  0  0  0  0 72]
 [ 0  0  0  0  0 72]
 [ 0  0  0  0  0 72]
 [ 0  0  0  0  0 72]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        72
           1       0.00      0.00      0.00        72
           2       0.00      0.00      0.00        72
           3       0.00      0.00      0.00        72
           4       0.00      0.00      0.00        72
           5       0.17      1.00      0.29        72

    accuracy                           0.17       432
   macro avg       0.03      0.17      0.05       432
weighted avg       0.03      0.17      0.05       432



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
poly = svm.SVC(kernel='poly', degree=5, C=1).fit(x_train, y_train)
y_pred=poly.predict(x_test)
print("Polynomial Classifier-->",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Polynomial Classifier--> 0.39351851851851855
[[16  7  6  4 36  3]
 [ 0 55  0 10  5  2]
 [16  1 36  0 17  2]
 [ 1  7  0 35 17 12]
 [ 1 49  1  0 19  2]
 [ 0 62  1  0  0  9]]
              precision    recall  f1-score   support

           0       0.47      0.22      0.30        72
           1       0.30      0.76      0.43        72
           2       0.82      0.50      0.62        72
           3       0.71      0.49      0.58        72
           4       0.20      0.26      0.23        72
           5       0.30      0.12      0.18        72

    accuracy                           0.39       432
   macro avg       0.47      0.39      0.39       432
weighted avg       0.47      0.39      0.39       432



In [ ]:
sig = svm.SVC(kernel='sigmoid', C=1).fit(x_train, y_train)
y_pred=sig.predict(x_test)
print("Sigmoidal Classifier-->",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Sigmoidal Classifier--> 0.12731481481481483
[[ 0 54  0  0 18  0]
 [ 0 22  0  1 49  0]
 [ 0 46  0  4 22  0]
 [ 0 54  0  5 13  0]
 [ 0 44  0  0 28  0]
 [ 0  0  0 16 56  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        72
           1       0.10      0.31      0.15        72
           2       0.00      0.00      0.00        72
           3       0.19      0.07      0.10        72
           4       0.15      0.39      0.22        72
           5       0.00      0.00      0.00        72

    accuracy                           0.13       432
   macro avg       0.07      0.13      0.08       432
weighted avg       0.07      0.13      0.08       432



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
